import { useState, useEffect } from "react";
import type { GraphData } from "@/lib/types";

declare global {
  interface Window {
    __GRAPH_DATA__?: GraphData;
  }
}

export function useGraphData() {
  const [data, setData] = useState<GraphData | null>(
    window.__GRAPH_DATA__ ?? null,
  );
  const [loading, setLoading] = useState(!window.__GRAPH_DATA__);

  useEffect(() => {
    if (window.__GRAPH_DATA__) return;

    // Load from static JSON (generated by scripts/extract-graph.js)
    fetch("/graph-data.json")
      .then((r) => {
        if (!r.ok) throw new Error("graph-data.json not found");
        return r.json();
      })
      .then((d: GraphData) => {
        setData(d);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to load graph data:", err);
        setLoading(false);
      });
  }, []);

  // SSE live reload (when served by graph dev server)
  useEffect(() => {
    if (window.__GRAPH_DATA__) return;

    let es: EventSource | null = null;
    try {
      es = new EventSource("/events");
      es.addEventListener("reload", () => {
        fetch("/graph-data.json")
          .then((r) => r.json())
          .then((d: GraphData) => setData(d));
      });
    } catch {
      // SSE not available
    }
    return () => es?.close();
  }, []);

  return { data, loading };
}
