/**
 * Step 09 — Generate rules files for non-Claude tools.
 * Only runs if we're in a project directory (has .git or .composure/).
 */

import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { logger } from "../lib/logger.js";
import { commandExists, execSafe } from "../lib/exec.js";

interface AdapterDef {
  file: string;
  template: string;
}

const ADAPTERS: Record<string, AdapterDef> = {
  cursor: {
    file: ".cursorrules",
    template: `# Composure Rules for Cursor
# Generated by create-composure
# See: https://composure-pro.com/docs/cursor
#
# Composure enforces code quality patterns across AI coding tools.
# These rules mirror the Claude Code enforcement hooks.
#
# Load shared config from ~/.composure/ if it exists.
# Run \`composure-enforce adapt cursor\` to regenerate.

## Code Quality
- Never rewrite working components — always extend/modify
- Check existing patterns in neighboring files before writing new code
- Follow the project's established naming conventions
- Respect multi-tenant isolation patterns (RLS, feed fields)

## Process
- Read files before modifying them
- Run tests after changes
- Don't add features beyond what was asked
`,
  },
  windsurf: {
    file: ".windsurfrules",
    template: `# Composure Rules for Windsurf
# Generated by create-composure
# See: https://composure-pro.com/docs/windsurf

## Code Quality
- Never rewrite working components — always extend/modify
- Check existing patterns in neighboring files before writing new code
- Follow the project's established naming conventions

## Process
- Read files before modifying them
- Run tests after changes
- Don't add features beyond what was asked
`,
  },
  gemini: {
    file: ".gemini/settings.json",
    template: `{
  "composure": true,
  "rules": [
    "Never rewrite working components — always extend/modify",
    "Check existing patterns in neighboring files before writing new code",
    "Read files before modifying them",
    "Run tests after changes"
  ]
}
`,
  },
  codex: {
    file: "codex.md",
    template: `# Composure Rules for Codex
# Generated by create-composure

- Never rewrite working components — always extend/modify
- Check existing patterns in neighboring files before writing new code
- Read files before modifying them
- Run tests after changes
- Don't add features beyond what was asked
`,
  },
};

export async function generateAdapters(options: {
  skipAdapters: boolean;
  selectedTools: string[];
}): Promise<{ generated: string[] }> {
  if (options.skipAdapters) {
    return { generated: [] };
  }

  // Only generate if we're in a project directory
  const cwd = process.cwd();
  const isProject = existsSync(join(cwd, ".git")) ||
    existsSync(join(cwd, ".composure")) ||
    existsSync(join(cwd, "package.json"));

  if (!isProject) {
    logger.info("Not in a project directory — skipping adapter generation");
    return { generated: [] };
  }

  const generated: string[] = [];

  // Try composure-enforce first (more comprehensive adapters)
  if (commandExists("composure-enforce") || commandExists("node")) {
    for (const tool of options.selectedTools) {
      if (tool === "claude") continue; // Claude uses hooks, not rules files

      // Try the enforce CLI if available
      const enforceResult = await execSafe("composure-enforce", ["adapt", tool]);
      if (enforceResult.exitCode === 0) {
        generated.push(tool);
        continue;
      }

      // Fall back to built-in templates
      const adapter = ADAPTERS[tool];
      if (adapter && !existsSync(join(cwd, adapter.file))) {
        // Create parent directory if needed (e.g., .gemini/)
        const dir = join(cwd, adapter.file, "..");
        if (adapter.file.includes("/")) {
          const { mkdirSync } = await import("node:fs");
          mkdirSync(dir, { recursive: true });
        }
        writeFileSync(join(cwd, adapter.file), adapter.template, "utf-8");
        generated.push(tool);
      }
    }
  }

  return { generated };
}
